name: Codecov

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run code coverage
    steps:
    - uses: actions/checkout@v1
    - name: Install dev requirements
      run: pip install -r dev-requirements.txt
    - name: Install pytest-cov
      run: pip install pytest-cov
    - name: Install package
      run: pip install .
    - name: Run tests and collect coverage
      run: pytest --cov .
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
